#include "input.h"

void specialKeys(int key, int, int)
{
    if (key == GLUT_KEY_SHIFT_L)
        keyShift = true;
}

void specialKeysUp(int key, int, int)
{
    if (key == GLUT_KEY_SHIFT_L)
        keyShift = false;
}

void keyboard(unsigned char key, int, int)
{
    switch (key)
    {
    case 27:
        std::exit(0);
        break;

    case 'w':
    case 'W':
        keyW = true;
        break;

    case 's':
    case 'S':
        keyS = true;
        break;

    case 'a':
    case 'A':
        keyA = true;
        break;

    case 'd':
    case 'D':
        keyD = true;
        break;

    case 'q':
    case 'Q':
        yawAngle -= turnSpeed;
        break;

    case 'e':
    case 'E':
        yawAngle += turnSpeed;
        break;

    case ' ':
        keySpace = true;
        break;

    case 't':
    case 'T':
        pitchAngle += pitchSpeed;
        if (pitchAngle > 89.0f) pitchAngle = 89.0f;
        break;

    case 'g':
    case 'G':
        pitchAngle -= pitchSpeed;
        if (pitchAngle < -89.0f) pitchAngle = -89.0f;
        break;
    }

    glutPostRedisplay();
}

void keyboardUp(unsigned char key, int, int)
{
    switch (key)
    {
    case 'w':
    case 'W':
        keyW = false;
        break;

    case 's':
    case 'S':
        keyS = false;
        break;

    case 'a':
    case 'A':
        keyA = false;
        break;

    case 'd':
    case 'D':
        keyD = false;
        break;

    case ' ':
        keySpace = false;
        break;
    }
}

void mouseLook(int x, int y)
{
    int centerX = windowWidth / 2;
    int centerY = windowHeight / 2;

    // ignore the fake event generated by glutWarpPointer
    if (ignoreWarp)
    {
        ignoreWarp = false;
        return;
    }

    int dx = x - centerX;
    int dy = y - centerY;

    yawAngle -= dx * mouseSensitivity;
    pitchAngle -= dy * mouseSensitivity;

    if (pitchAngle > 89.0f) pitchAngle = 89.0f;
    if (pitchAngle < -89.0f) pitchAngle = -89.0f;

    ignoreWarp = true;
    glutWarpPointer(centerX, centerY);

    glutPostRedisplay();
}
